it.skip('should ', () => {
    cy.get('#react-burger-menu-btn').click()
    cy.get('#logout_sidebar_link').click()
    cy.get('#login-button').should('be.visible')
    cy.get('#user-name').type(Cypress.env('glitchUsername'))
    cy.get('#password').type(Cypress.env('password'))
    cy.window()
        .its('performance')
        .invoke('mark', 'loginButtonIsClicked')
    cy.get('#login-button').click()
    cy.get('#login-button').should('not.exist')
    cy.get('.shopping_cart_link').should('be.visible')
    cy.window()
        .its('performance')
        .invoke('measure', 'loginButtonClick')
        .its('duration', {timeout: 0})
        .should('be.lessThan', 5000)
})